### ISSUE TITLE
Does not start up on SL6.5

### ISSUE THREAD

**Issue by DirkHoffmann** [nuxeo/nuxeo-drive#49]
I installed nuxe-drive on a Scientific Linux 6 instance. I am not sure, if this is a bug, or if I misunderstood some installation instructions. In any case, there is potential to improve the precision of the error message :wink: 

```
$ ndrive
Traceback (most recent call last):
  File "/usr/bin/ndrive", line 6, in <module>
    sys.exit(main())
  File "/usr/lib/python2.6/site-packages/nxdrive/commandline.py", line 793, in main
    return CliHandler().handle(argv)
  File "/usr/lib/python2.6/site-packages/nxdrive/commandline.py", line 481, in handle
    self._configure_logger(options)
  File "/usr/lib/python2.6/site-packages/nxdrive/commandline.py", line 455, in _configure_logger
    command_name=options.command,
  File "/usr/lib/python2.6/site-packages/nxdrive/logging_config.py", line 93, in configure
    console_handler.set_name(console_handler_name)
AttributeError: StreamHandler instance has no attribute 'set_name'
```

**Comment by ataillefer** [comment]
Means the logging module you're using doesn't have the right API, I can see you're in Python 2.6 whereas Drive is currently build on the top of Python 2.7.6. You should try installing Python 2.7.x.

**Comment by ataillefer** [comment]
And the error message is provided by Python...

**Comment by DirkHoffmann** [comment]
I conclude that massive installation is not possible on Scientific Linux 6(.5) for the time being. Upgrading python outside SL repository-provided packages is not an option.

**Comment by DirkHoffmann** [comment]
Proposal for improving the error message, if 2.6 is not working: Use `sys.version_info[]` to indicate this fact clearly to the user on startup.
I can provide the PR for that. But is it agreed that python < 2.7 will *not* run nuxeo-drive?

**Comment by DirkHoffmann** [comment]
Should the 2.7 requirement be added in README.md?

**Comment by ataillefer** [comment]
Yes:
- Displaying a clear message would be nice, for which you are welcome to provide a PR.
- Python < 2.7 is not tested at Nuxeo so we won't make Drive run against it (especially as we might be targetting Python 3 one of these days :))
- 2.7 requirement should be in the README.

Thanks.

**Comment by DirkHoffmann** [comment]
Today (1:02am) Antoine Taillefer wrote:

> 
> Yes:
>
>  *  Displaying a clear message would be nice, for which you are welcome to
>     provide a PR.
>  *  Python < 2.7 is not tested at Nuxeo so we won't make Drive run against
>     it (especially as we might be targetting Python 3 one of these days :))
>  *  2.7 requirement should be in the README.

OK. Give me a day or so. And thanks for your quick replies!

**Comment by DirkHoffmann** [comment]
Today (1:42am) Antoine Taillefer wrote:

> 
> Closed #49.

Rather assign to me for followup?

(I understood you want something from me now :-)

Up to you ...

**Comment by ataillefer** [comment]
OK I thought you would create a Pull Request, which is different from an issue, feel free to link the issue to a PR (I think you can also convert an issue to a PR...).

**Comment by DirkHoffmann** [comment]
Today (2:25am) Antoine Taillefer wrote:

> 
> OK I thought you would create a Pull Request, which is different from an
> issue, feel free to link the issue to a PR (I think you can also convert an
> issue to a PR...).

Yes. That is details of issue management. Never mind.

Didn't know, if you read the fine-print. ;-)

**Comment by DirkHoffmann** [comment]
Now only one part of this ticket remains to do:
> * Displaying a clear message would be nice, for which you are welcome to provide a PR.

I will do as good as I can figure out. But if you have advice on coding conventions where to put the check, how to issue the warning … you are welcome!
